---
name: 🐛 Bug Report
description: Report a bug or issue with this civic tech project
title: '[BUG] '
labels: ['bug', 'needs-triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Help us understand what went wrong so we can fix it quickly.

  - type: checkboxes
    id: impact-level
    attributes:
      label: Bug Impact Level
      description: How does this bug affect community members?
      options:
        - label: Critical - Prevents essential community services/access
        - label: High - Significantly impacts user experience
        - label: Medium - Causes frustration but workarounds exist
        - label: Low - Minor cosmetic or edge case issue
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: What happened? Be clear and concise.
      placeholder: Describe what you observed that was incorrect or unexpected.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened instead?
      placeholder: Describe what you expected to see or happen.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: dropdown
    id: user-type
    attributes:
      label: User Type Affected
      description: What type of user experienced this bug?
      options:
        - Community resident
        - City staff/official
        - Nonprofit organization member
        - Developer/contributor
        - Volunteer/activist
        - Other community member
        - Not sure
    validations:
      required: true
  - type: checkboxes
    id: accessibility-impact
    attributes:
      label: Accessibility Impact
      description: Does this bug affect accessibility?
      options:
        - label: Bug affects screen reader users
        - label: Bug affects keyboard navigation
        - label: Bug affects color/contrast visibility
        - label: Bug affects mobile users
        - label: Bug creates barriers for users with disabilities
        - label: No accessibility impact
  - type: dropdown
    id: browsers
    attributes:
      label: Browser/Platform
      description: What browser or platform were you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile Safari (iOS)
        - Mobile Chrome (Android)
        - Other mobile browser
        - Desktop application
        - Other (please specify)
    validations:
      required: true
  - type: input
    id: browser-version
    attributes:
      label: Browser/Platform Version
      description: What version of the browser or platform?
      placeholder: e.g., Chrome 118, iOS 17, Windows 11
  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      description: What type of device were you using?
      options:
        - Desktop/Laptop
        - Mobile Phone
        - Tablet
        - Assistive Technology (screen reader, etc.)
        - Other
  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages
      description: Were there any error messages? Include exact text.
      placeholder: Copy and paste any error messages you saw.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Screen Recording
      description: If applicable, add screenshots to help explain the problem.
      placeholder: Drag and drop images here, or paste image URLs.
  - type: textarea
    id: workaround
    attributes:
      label: Current Workaround
      description: Have you found a way to work around this issue?
      placeholder: Describe any temporary solutions you're using.
  - type: checkboxes
    id: frequency
    attributes:
      label: Bug Frequency
      description: How often does this bug occur?
      options:
        - label: Always - Happens every time
        - label: Often - Happens most of the time
        - label: Sometimes - Happens occasionally
        - label: Rarely - Hard to reproduce
        - label: Once - Only happened one time
  - type: textarea
    id: community-impact
    attributes:
      label: Community Impact
      description: How does this bug affect the community or project goals?
      placeholder: |
        - Number of users potentially affected: [estimate]
        - Community services impacted: [list services]
        - DVF score impact: [which areas affected]
        - Urgency for community: [timeline needs]
  - type: checkboxes
    id: testing-help
    attributes:
      label: Testing Assistance
      options:
        - label: I can help test the fix
        - label: I can provide more details if needed
        - label: I can connect you with affected community members
        - label: I can help document the solution
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information about the bug?
      placeholder: Add any other context, links, or information that might be helpful.
