name: 🤝 Community Partnership
description: Track community partnerships and stakeholder engagement
title: '[PARTNERSHIP] '
labels: ['community-partner', 'stakeholder']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Community partnerships are essential for successful civic tech projects. Track your stakeholder relationships here.

  - type: dropdown
    id: partnership-stage
    attributes:
      label: Partnership Stage
      description: What stage is this partnership in?
      options:
        - Initial outreach - First contact
        - Relationship building - Getting to know each other
        - Active collaboration - Working together on project
        - Partnership evaluation - Assessing partnership success
        - Partnership renewal - Extending collaboration
        - Partnership completion - Wrapping up collaboration
    validations:
      required: true

  - type: input
    id: organization-name
    attributes:
      label: Partner Organization
      description: Name of the community organization or stakeholder
      placeholder: e.g., Waterloo Region Housing, United Way, City of Kitchener
    validations:
      required: true

  - type: dropdown
    id: partner-type
    attributes:
      label: Partner Type
      description: What type of organization is this?
      options:
        - Municipal government
        - Regional government
        - Provincial government
        - Federal government
        - Nonprofit organization
        - Community service organization
        - Educational institution
        - Healthcare organization
        - Faith-based organization
        - Business/Private sector
        - Community group/Association
        - Individual community leader
        - Other
    validations:
      required: true

  - type: input
    id: contact-person
    attributes:
      label: Primary Contact Person
      description: Who is the main contact at this organization?
      placeholder: Name and role (keep contact details in private notes)

  - type: textarea
    id: partnership-goals
    attributes:
      label: Partnership Goals
      description: What do we hope to achieve through this partnership?
      placeholder: |
        - Access to [specific user group or data]
        - Validation of [project approach or requirements]
        - Distribution/promotion through [partner channels]
        - Long-term sustainability through [ongoing relationship]
        - Domain expertise in [specific area]
    validations:
      required: true

  - type: textarea
    id: partner-needs
    attributes:
      label: Partner Needs & Interests
      description: What does the partner organization need or want from this collaboration?
      placeholder: |
        - Technology solution for [specific problem]
        - Community engagement around [issue]
        - Data or insights about [topic]
        - Volunteer support for [activities]
        - Increased visibility for [cause/services]

  - type: textarea
    id: value-exchange
    attributes:
      label: Value Exchange
      description: What value does each party bring to the partnership?
      placeholder: |
        ## What we provide to partner:
        - [Technical expertise, volunteer time, etc.]

        ## What partner provides to us:
        - [Domain knowledge, user access, data, etc.]

  - type: dropdown
    id: engagement-frequency
    attributes:
      label: Engagement Frequency
      description: How often do you plan to interact with this partner?
      options:
        - Weekly check-ins
        - Bi-weekly meetings
        - Monthly updates
        - Quarterly reviews
        - As-needed basis
        - One-time collaboration
        - To be determined
    validations:
      required: true

  - type: checkboxes
    id: collaboration-activities
    attributes:
      label: Collaboration Activities
      description: What activities will you do together?
      options:
        - label: User research and interviews
        - label: Requirements gathering and validation
        - label: Solution co-design sessions
        - label: User testing and feedback
        - label: Data sharing and analysis
        - label: Content creation and review
        - label: Community outreach and promotion
        - label: Training and capacity building
        - label: Ongoing service delivery
        - label: Impact measurement and evaluation

  - type: textarea
    id: dvf-impact
    attributes:
      label: DVF Impact
      description: How does this partnership affect our DVF scorecard?
      placeholder: |
        - Community Partner score: [expected impact]
        - Talent & Team: [skills/capacity gained]
        - Technically Exciting: [technical validation/requirements]
        - Civic Exciting: [community reach/impact enhanced]

  - type: checkboxes
    id: partnership-stage-activities
    attributes:
      label: Current Activities
      description: What are you working on with this partner right now?
      options:
        - label: Initial introduction and relationship building
        - label: Needs assessment and requirement gathering
        - label: Solution validation and feedback
        - label: User research coordination
        - label: Data access and sharing agreements
        - label: Community testing and pilots
        - label: Marketing and promotion planning
        - label: Sustainability and handoff planning
        - label: Impact measurement and reporting

  - type: textarea
    id: challenges-barriers
    attributes:
      label: Challenges & Barriers
      description: What obstacles or concerns need to be addressed?
      placeholder: |
        - Privacy/legal concerns about [specific issue]
        - Resource constraints: [time, staff, technology]
        - Misaligned expectations about [specific area]
        - Communication challenges: [language, timing, etc.]
        - Technical barriers: [system integration, data formats, etc.]

  - type: textarea
    id: success-metrics
    attributes:
      label: Partnership Success Metrics
      description: How will you know if this partnership is successful?
      placeholder: |
        - Partner satisfaction: [how measured]
        - Project impact: [specific outcomes]
        - Relationship quality: [ongoing engagement indicators]
        - Mutual benefit: [value delivered to both parties]

  - type: input
    id: timeline-milestones
    attributes:
      label: Key Timeline & Milestones
      description: Important dates and deadlines for this partnership
      placeholder: e.g., Initial meeting by Week 3, User testing in Week 8, Final report by Week 12

  - type: checkboxes
    id: communication-preferences
    attributes:
      label: Partner Communication Preferences
      description: How does this partner prefer to communicate?
      options:
        - label: Email updates
        - label: Phone calls
        - label: In-person meetings
        - label: Video conferences
        - label: Formal reports/documentation
        - label: Informal check-ins
        - label: Community events/presentations

  - type: textarea
    id: partnership-agreement
    attributes:
      label: Partnership Agreement Status
      description: Are there any formal agreements or MOUs in place?
      placeholder: |
        - Formal agreement needed: [Yes/No]
        - Data sharing agreement: [Status]
        - Volunteer agreement: [Status]
        - Intellectual property considerations: [Notes]

  - type: checkboxes
    id: help-needed
    attributes:
      label: Support Needed
      description: What help do you need with this partnership?
      options:
        - label: Help with initial outreach
        - label: Assistance with meeting facilitation
        - label: Support with legal/privacy questions
        - label: Help with technical integration
        - label: Community introduction/connections
        - label: CTWR organizational support
        - label: Documentation and reporting help

  - type: textarea
    id: next-steps
    attributes:
      label: Next Steps
      description: What are the immediate next actions for this partnership?
      placeholder: |
        - [ ] Schedule follow-up meeting by [date]
        - [ ] Prepare [specific deliverable] for partner review
        - [ ] Connect partner with [specific team member/resource]
        - [ ] Review and address [specific concern/question]

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any other relevant information about this partnership?
      placeholder: Background context, previous relationships, special considerations, etc.
