---
name: 🚀 Feature Request
description: Propose a new feature for this civic tech project
title: '[FEATURE] '
labels: ['enhancement', 'needs-triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Help us understand how this will benefit our community.

  - type: checkboxes
    id: dvf-category
    attributes:
      label: DVF Impact Category
      description: Which DVF areas does this feature primarily impact?
      options:
        - label: Community Partner - Improves stakeholder engagement
        - label: Talent & Team - Enhances team productivity or skills
        - label: Technically Exciting - Introduces new technology or innovation
        - label: Civic Exciting - Increases community impact or accessibility

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Describe this feature from the user's perspective
      placeholder: 'As a [type of user], I want [goal] so that [benefit to community/user].'
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What community problem does this feature address?
      placeholder: Describe the current pain point or gap in service for community members.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would this feature work?
      placeholder: Describe your proposed solution and how users would interact with it.
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: Primary User Type
      description: Who would primarily benefit from this feature?
      options:
        - Community residents
        - City staff/officials
        - Nonprofit organizations
        - Volunteers/activists
        - Developers/contributors
        - Other community stakeholders
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What specific requirements must be met for this feature to be complete?
      placeholder: |
        - [ ] Users can [specific action]
        - [ ] System responds with [expected behavior]
        - [ ] Accessibility standards are met (WCAG 2.1)
        - [ ] Works on mobile devices
        - [ ] Performance impact is minimal
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature for the community?
      options:
        - Critical - Blocks core functionality or serves urgent community need
        - High - Significant community benefit, should be in current season
        - Medium - Good to have, could be implemented in future seasons
        - Low - Nice enhancement, low community impact
    validations:
      required: true

  - type: checkboxes
    id: accessibility
    attributes:
      label: Accessibility Considerations
      description: Have you considered how this feature works for all community members?
      options:
        - label: Feature works with screen readers
        - label: Feature works with keyboard-only navigation
        - label: Feature has sufficient color contrast
        - label: Feature works on mobile devices
        - label: Feature supports multiple languages (if applicable)
        - label: I need help evaluating accessibility

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What other approaches could solve this problem?
      placeholder: Describe any alternative solutions you've considered.

  - type: textarea
    id: community-research
    attributes:
      label: Community Research
      description: Have you validated this need with community members?
      placeholder: |
        - User interviews conducted: [number/details]
        - Community feedback received: [source/summary]
        - Similar solutions researched: [what exists elsewhere]
        - Partner organization input: [stakeholder feedback]

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Considerations
      options:
        - label: I can help implement this feature
        - label: I can help with user testing
        - label: I can help with user research
        - label: I can connect with community partners
        - label: I can provide domain expertise

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that would help evaluate this feature?
      placeholder: Screenshots, mockups, links to similar features, etc.
