name: 👥 User Research
description: Plan user research activities or report research findings
title: '[RESEARCH] '
labels: ['user-research', 'community']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        User research is essential for civic tech! Help us understand community needs and validate our solutions.

  - type: dropdown
    id: research-type
    attributes:
      label: Research Type
      description: What type of research activity is this?
      options:
        - Plan user interviews
        - Conduct user surveys
        - Report research findings
        - Usability testing
        - Community feedback session
        - Stakeholder interviews
        - Accessibility testing
        - Other research activity
    validations:
      required: true

  - type: textarea
    id: research-goals
    attributes:
      label: Research Goals
      description: What do we want to learn from this research?
      placeholder: |
        - Understand how community members currently [process/task]
        - Validate that our solution addresses [specific problem]
        - Identify barriers to using [feature/service]
        - Test usability of [specific functionality]
    validations:
      required: true

  - type: dropdown
    id: target-users
    attributes:
      label: Target User Group
      description: Who should participate in this research?
      options:
        - General community residents
        - Seniors (65+)
        - Newcomers to Canada
        - Low-income community members
        - People with disabilities
        - City staff/officials
        - Nonprofit organization staff
        - Small business owners
        - Students
        - Parents/caregivers
        - Other specific group
    validations:
      required: true

  - type: input
    id: participant-count
    attributes:
      label: Number of Participants Needed
      description: How many people do you want to include?
      placeholder: e.g., 5-8 interviews, 50+ survey responses

  - type: textarea
    id: research-questions
    attributes:
      label: Key Research Questions
      description: What specific questions do we need answered?
      placeholder: |
        1. How do you currently [relevant process]?
        2. What challenges do you face when [specific task]?
        3. What would make [process] easier for you?
        4. How do you typically find information about [topic]?
    validations:
      required: true

  - type: checkboxes
    id: research-methods
    attributes:
      label: Research Methods
      description: What research methods will you use?
      options:
        - label: One-on-one interviews (30-45 minutes)
        - label: Group interviews/focus groups
        - label: Online surveys
        - label: Usability testing sessions
        - label: Observational research
        - label: Community workshops
        - label: Accessibility testing with assistive technology
        - label: Street interviews/intercepts

  - type: textarea
    id: recruitment-plan
    attributes:
      label: Participant Recruitment Plan
      description: How will you find and recruit participants?
      placeholder: |
        - Partner organizations to connect with: [list]
        - Community locations to visit: [list]
        - Online channels to use: [social media, forums, etc.]
        - Incentives/compensation planned: [gift cards, etc.]
        - Accessibility accommodations: [language, location, etc.]

  - type: checkboxes
    id: accessibility-considerations
    attributes:
      label: Accessibility & Inclusion
      description: How will you ensure inclusive research?
      options:
        - label: Provide multiple language options
        - label: Offer flexible scheduling (evenings/weekends)
        - label: Choose accessible meeting locations
        - label: Provide virtual participation options
        - label: Include participants with disabilities
        - label: Consider low-tech/no-tech alternatives
        - label: Account for different economic situations

  - type: textarea
    id: dvf-connection
    attributes:
      label: DVF Framework Connection
      description: How does this research connect to our DVF scorecard?
      placeholder: |
        - Community Partner: [how this validates partner needs]
        - Talent & Team: [skills needed, community involvement]
        - Technically Exciting: [technical validation needed]
        - Civic Exciting: [community impact validation]

  - type: dropdown
    id: timeline
    attributes:
      label: Research Timeline
      description: When do you plan to complete this research?
      options:
        - Week 1-3 (Project initialization)
        - Week 4-6 (Development phase)
        - Week 7-9 (Testing phase)
        - Week 10-11 (Demo preparation)
        - Ongoing throughout season
        - After current season
    validations:
      required: true

  - type: textarea
    id: research-findings
    attributes:
      label: Research Findings (if reporting)
      description: If this is a research report, what did you learn?
      placeholder: |
        ## Key Insights
        1. [Major finding with supporting evidence]
        2. [Major finding with supporting evidence]

        ## User Quotes
        - "[Memorable quote that captures user perspective]"
        - "[Another impactful quote]"

        ## Recommendations
        - [Specific action items based on research]
        - [Priority changes to consider]

  - type: checkboxes
    id: ethics-privacy
    attributes:
      label: Ethics & Privacy
      description: Research ethics and privacy considerations
      options:
        - label: Participants will provide informed consent
        - label: Personal information will be anonymized
        - label: Recordings will be stored securely and deleted after analysis
        - label: Participants can withdraw at any time
        - label: Research follows CTWR privacy guidelines
        - label: Community partners have approved research approach

  - type: checkboxes
    id: help-needed
    attributes:
      label: Help Needed
      description: What support do you need for this research?
      options:
        - label: Help recruiting participants
        - label: Help conducting interviews
        - label: Help with survey design
        - label: Help analyzing results
        - label: Connections to community organizations
        - label: Translation/interpretation support
        - label: Technical setup for remote research

  - type: textarea
    id: next-steps
    attributes:
      label: Next Steps
      description: What happens after this research?
      placeholder: |
        - Analysis timeline: [when will results be available]
        - How results will be shared: [team meeting, documentation, etc.]
        - Expected impact on project: [design changes, feature priorities, etc.]
        - Follow-up research planned: [what additional research needed]

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information?
      placeholder: Links to research plans, previous findings, partner requirements, etc.
