title: "CivicTechWR Project Template"
description: "CivicTechWR Season X Project Template - A comprehensive template for civic tech projects"
url: "https://civictechwr.github.io"
baseurl: "/CTWR-Project-Template-New"
repository: "CivicTechWR/CTWR-Project-Template-New"

# Theme
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# CivicTechWR branding
header_pages:
  - about.md
  - team.md
  - demo.md
  - docs.md

# Author information
author:
  name: "CivicTechWR Team"
  email: "noreply@civictechwr.org"

# Social links
github_username: CivicTechWR
civictech_url: "https://civictechwr.org"

# Site settings
lang: en
timezone: America/Toronto

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - README.md

# Include additional files
include:
  - _pages

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "CivicTechWR Team"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"

# Custom variables for CivicTechWR projects
civictech:
  season: "X"
  dvf_score: "[/20]"
  partner: "[Partner Organization]"
  status: "[Research/Development/Testing/Live]"
  demo_day: "[Date]"

# Analytics (use privacy-focused options for civic projects)
# google_analytics: false  # Avoid for government/civic data
# Add privacy-focused analytics configuration here if needed